name: MailPlugin
version: '1.0'
main: org.mythofy.mailplugin.MailPlugin
api-version: '1.20'

commands:
  mail:
    description: Opens the mail GUI
    usage: /mail open
  confirmmailrecipient:
    description: Confirms the mail recipient
    usage: /confirmmailrecipient
  confirmmailmessage:
    description: Confirms the mail message
    usage: /confirmmailmessage
  confirmgiftsend:
    description: Confirms sending the gift
    usage: /confirmgiftsend
  cancelmailaction:
    description: Cancels the mail action
    usage: /cancelmailaction
  cancelgiftaction:
    description: Cancels the gift action
    usage: /cancelgiftaction
